name: Release MCPB Package

on:
  release:
    types:
      - published

permissions:
  contents: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.23

      - name: Set package version
        env:
          VERSION: ${{ github.ref_name }}
        run: |
          echo $(jq --arg v "${{ env.VERSION }}" '(.version) = $v' package.json) > package.json
          echo $(jq --arg v "${{ env.VERSION }}" '(.version) = $v' manifest.json) > manifest.json

      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: Build
        run: bun run build

      - name: Pack MCPB
        run: bunx @anthropic-ai/mcpb pack

      - name: Clean MCPB
        run: bunx @anthropic-ai/mcpb clean mcp.mcpb

      - name: Upload MCPB to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: mcp.mcpb
          fail_on_unmatched_files: true
