name: Release NPM Package

on:
  release:
    types:
      - published

permissions:
  contents: read
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.23

      - name: Set package version
        env:
          VERSION: ${{ github.ref_name }}
        run: |
          echo $(jq --arg v "${{ env.VERSION }}" '(.version) = $v' package.json) > package.json
          echo $(jq --arg v "${{ env.VERSION }}" '(.version) = $v' manifest.json) > manifest.json

      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: Publish
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}
          TAG: ${{ github.event.release.prerelease && 'canary' || 'latest' }}
        run: bun publish --tag=${{ env.TAG }}
