name: Release

on:
  release:
    types:
      - published

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.17

      - name: Set package version
        env:
          VERSION: ${{ github.ref_name }}
        run: |
          echo $(jq --arg v "${{ env.VERSION }}" '(.version) = $v' package.json) > package.json

      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: Publish
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}
          TAG: ${{ github.event.release.prerelease && 'canary' || 'latest' }}
        run: bun publish --tag=${{ env.TAG }}
